### ISSUE TITLE
Add bluetooth tests

### ISSUE THREAD

**Issue by abhijit-mahajani-imgtec** [CreatorDev/board-test#16]
Since https://github.com/CreatorDev/openwrt/pull/99 is adding support for bluetooth and btle. we should add the respective tests in the board-test too.

**Comment by Shpinkso** [comment]
Presumably this is intended to be "add BT tests to CI"? Can you link to the tests you reference too? Can't see anything obvious.

**Comment by Ham22** [comment]
Blocked waiting for bluetooth support to be merged
